### ISSUE TITLE
GitHub Action with this Action Starting to Fail 7/21/2021

### ISSUE THREAD

**Issue by SamChristiansen** [ridedott/merge-me-action#1012]
**How would you describe the issue?**

We are using this action to auto-merge dependabot PRs, and this has been consistently working well for us (thanks!). This morning, I had some dependabot PRs that passed all checks but weren't being auto-merge. Our github action that auto-merges was failing with this error:

```
Run ridedott/merge-me-action@v2
  with:
    GITHUB_TOKEN: ***
    GITHUB_LOGIN: dependabot
    ENABLE_GITHUB_API_PREVIEW: false
    MERGE_METHOD: SQUASH
    ENABLED_FOR_MANUAL_CHANGES: false
    MAXIMUM_RETRIES: 3
Automatic merges enabled for GitHub login: dependabot.
Error: An unexpected error occurred: Cannot read property 'endCursor' of undefined, TypeError: Cannot read property 'endCursor' of undefined
    at makeGraphqlIterator (/home/runner/work/_actions/ridedott/merge-me-action/v2/webpack:/@ridedott/merge-me-action/src/common/makeGraphqlIterator.ts:50:1)
    at process.node (internal/process/task_queues.js:93:5)
    at branchProtectionRules (/home/runner/work/_actions/ridedott/merge-me-action/v2/webpack:/@ridedott/merge-me-action/src/common/listBranchProtectionRules.ts:50:1)
    at continuousIntegrationEndHandle (/home/runner/work/_actions/ridedott/merge-me-action/v2/webpack:/@ridedott/merge-me-action/src/eventHandlers/continuousIntegrationEnd/index.ts:80:1).
```

I'm guessing the latest release of this action broke something.

**How can we reproduce the issue?**

It looks like it is happening on all of our repos that use this action, so it should be easy to repeat. Here is the bit of our yml file that uses the action:

```
merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**What are the expected results?**

There shouldn't be an error while using the action.

**What are the actual results?**

The error is preventing the action from working correctly.

**How much does it hurt?**

This appears to be breaking the action.

**Comment by xtazz** [comment]
Hi Sam! Thanks for reporting the issue, this problem has been solved yesterday in version v2.9.1. Original issue https://github.com/ridedott/merge-me-action/issues/1008

**Comment by SamChristiansen** [comment]
@xtazz Thanks for the update! I'm fairly new with GitHub actions, so I'm not sure how long it takes for releases to become available. We just had a handful a dependabot PRs come in and still fail with the same error above.  With our GitHub Action using `uses: ridedott/merge-me-action@v2`, do you know when our workflow will start picking up this new version? I did look at the [GitHub Marketplace page](https://github.com/marketplace/actions/merge-me) and it says the latest is 2.8.35. I don't know if that needs to be updated.
